---

version: '3'

services:

  postgres:
    image: 'postgres:9.6'
    environment:
      POSTGRES_USER: 'troposphere_db_user'
      POSTGRES_PASSWORD: 'troposphere_db_pass'
      POSTGRES_DB: 'troposphere_db'

  sut:
    build: .
    entrypoint: '/root/test.sh'
    depends_on:
      - 'postgres'
